import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#23005c',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'primary-fixed': '#d8e2ff',
        'on-tertiary-container': '#f5fff6',
        'tertiary-container': '#00855b',
        'on-primary-fixed-variant': '#004395',
        'on-error': '#ffffff',
        'inverse-surface': '#213145',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#6ffbbe',
        'inverse-primary': '#adc6ff',
        'primary-fixed-dim': '#adc6ff',
        'on-secondary-container': '#fffbff',
        'on-primary-container': '#fefcff',
        'primary': '#0058be',
        'surface-tint': '#005ac2',
        'surface-bright': '#f8f9ff',
        'secondary-fixed': '#e9ddff',
        'surface': '#f8f9ff',
        'secondary': '#6b38d4',
        'on-primary-fixed': '#001a42',
        'surface-dim': '#cbdbf5',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'secondary-container': '#8455ef',
        'on-secondary-fixed-variant': '#5516be',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'outline': '#727785',
        'surface-container': '#e5eeff',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#f8f9ff',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#005236',
        'outline-variant': '#c2c6d6',
        'secondary-fixed-dim': '#d0bcff',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'tertiary': '#006947',
        'surface-container-low': '#eff4ff',
        'surface-variant': '#d3e4fe',
        'primary-container': '#2170e4',
        'on-surface-variant': '#424754',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
} satisfies Config
